name: Prometheus client
dir: .
start_cmd: java -jar prom-client-ibmi.jar
check_alive: '9853'
batch_mode: 'false'

environment_vars:
- PATH=/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
- JAVA_HOME=/QOpenSys/QIBM/ProdData/JavaVM/jdk80/64bit

groups:
- autostart